apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: traefik-ingress-controller
---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: traefik
  labels:
    app: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:v2.10
          args:
            - --accesslog
            - --entrypoints.web.Address=:80
            - --entrypoints.web.http.redirections.entryPoint.to=websecure
            - --entrypoints.web.http.redirections.entryPoint.scheme=https
            - --entrypoints.web.http.redirections.entrypoint.permanent=true
            - --entrypoints.websecure.Address=:443
            - --entrypoints.websecure.http.tls.certresolver=defaultresolver
            - --entrypoints.websecure.http.middlewares=default-security-middleware@kubernetescrd
            - --entrypoints.websecure.http.tls.options=default-tls-option@kubernetescrd
            - --providers.kubernetescrd
            - --certificatesresolvers.defaultresolver.acme.tlschallenge
            - --certificatesresolvers.defaultresolver.acme.email=sam.leeflang@naturalis.nl
            - --certificatesresolvers.defaultresolver.acme.storage=acme.json
            - --metrics.prometheus=true
            - --providers.kubernetescrd.allowcrossnamespace=true
            - --entryPoints.websecure.forwardedHeaders.insecure=true
            - --entryPoints.websecure.forwardedHeaders.trustedIPs=192.168.32.0/19
            - --entryPoints.websecure.proxyProtocol.trustedIPs=192.168.32.0/19
            - --entryPoints.web.proxyProtocol.trustedIPs=192.168.32.0/19
            - --entryPoints.web.forwardedHeaders.trustedIPs=192.168.32.0/19
            - --entryPoints.web.forwardedHeaders.insecure=true
#            - --log.level=DEBUG
          ports:
            - name: web
              containerPort: 80
            - name: websecure
              containerPort: 443