mode: daemonset
image:
  repository: otel/opentelemetry-collector-k8s
# Presets configure specific collectors/receivers and add them to the relevant pipelines
presets:
  # Enables filelog receiver to collect logs
  logsCollection:
    enabled: true

  # Enables the Kubernetes attributes processor.
  # Discovers pods, extracts their metadata, adds metadata to spans/metrics/logs pipelines
  # Pipelines: all
  kubernetesAttributes:
    enabled: true
    extractAllPodLabels: true  # Adds pod labels as resources

  # Enables kubeletStat receiver (aka kubeletMetrics)
  # Collects node, pod, and container metrics from the API server on a kubelet
  # Pipeline: metrics
  kubeletMetrics:
    enabled: true

config:
  extensions:
    oauth2client/client:
      client_id: naturalis.bii.dissco
      client_secret: <secret>
      token_url: https://keycloak.iam.naturalis.io/realms/observability/protocol/openid-connect/token
      tls:
        insecure: true
  exporters:
    otlp/metrics:
      endpoint: https://metrics.gateway.analytics.naturalis.io:443
      auth:
        authenticator: oauth2client/client
    otlp/logs:
      endpoint: https://logs.gateway.analytics.naturalis.io:443
      auth:
        authenticator: oauth2client/client
  # Disable some of the helm chart's default configs
  receivers:
    jaeger: null
    zipkin: null
  service:
    extensions:
      - oauth2client/client
    pipelines:
      logs:
        exporters:
          - otlp/logs
        # Processors: memory_limiter, batch
        # Receivers: vanilla otlp, filelogs, kubernetesAttributes
      metrics:
        exporters:
          - otlp/metrics
        # Processors: memory_limiter, batch
        # Receivers: prometheus, vanilla otlp, kubernetesAttributes, kubeletMetrics

# Disable some default behaviour
ports:
  jaeger-compact:
    enabled: false
  jaeger-thrift:
    enabled: false
  jaeger-grpc:
    enabled: false
  zipkin:
    enabled: false