mode: deployment
image:
  repository: otel/opentelemetry-collector-k8s
# We only want one of these collectors - any more and we'd produce duplicate data
replicaCount: 1
presets:
  clusterMetrics:
    enabled: true
  kubernetesEvents:
    enabled: true
config:
  exporters:
    debug:
      verbosity: detailed
  service:
    pipelines:
      logs:
        exporters:
          - debug