apiVersion: apps/v1
kind: Deployment
metadata:
  name: dissco-digital-specimen-processor-web
  labels:
    app: dissco-digital-specimen-processor-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dissco-digital-specimen-processor-web
  template:
    metadata:
      labels:
        app: dissco-digital-specimen-processor-web
        language: java
    spec:
      automountServiceAccountToken: false
      containers:
        - name: dissco-digital-specimen-processor-web
          image: public.ecr.aws/dissco/dissco-core-digital-specimen-processor:sha-5389a90 # Nov 22
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: spring.profiles.active
              value: web
            - name: spring.datasource.url
              value: jdbc:postgresql://terraform-20241127102459386000000001.cbppwfnjypll.eu-west-2.rds.amazonaws.com:5432/dissco
            - name: spring.datasource.username
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: db-username
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: db-password
            - name: elasticsearch.hostname
              value: elastic-search-es-http.elastic.svc.cluster.local
            - name: elasticsearch.port
              value: "9200"
            - name: elasticsearch.username
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: elastic-username
            - name: elasticsearch.password
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: elastic-password
            - name: elasticsearch.index-name
              value: digital-specimen
            - name: kafka.publisher.host
              value: kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
            - name: kafka.consumer.host
              value: kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
            - name: kafka.consumer.group
              value: group
            - name: kafka.consumer.topic
              value: digital-specimen
            - name: spring.security.oauth2.resourceserver.jwt.issuer-uri
              value: https://login-demo.dissco.eu/auth/realms/dissco
            - name: auth.id
              value: production-dissco-processor
            - name: auth.grantType
              value: client_credentials
            - name: auth.tokenEndpoint
              value: https://login-demo.dissco.eu/auth/realms/dissco/protocol/openid-connect/token
            - name: handle.endpoint
              value: https://dissco.eu/doi-manager/api/v1/pids/
            - name: auth.secret
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: production-dissco-processor-token
            - name: caching.spring.ttl
              value: PT6H
          resources:
            requests:
              memory: "500Mi"
              cpu: "200m"
            limits:
              memory: "500Mi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 45
            failureThreshold: 2
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false