apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mas-secrets
  namespace: machine-annotation-services
spec:
  provider: aws
  secretObjects:
    - secretName: mas-secrets
      type: Opaque
      data:
        - objectName: geopick-user
          key: geopick-user
        - objectName: geopick-password
          key: geopick-password
        - objectName: bold-api-user
          key: bold-api-user
        - objectName: bold-api-password
          key: bold-api-password
        - objectName: mindat-api-key
          key: mindat-api-key
        - objectName: plant-organ-segmentation-user
          key: plant-organ-segmentation-user
        - objectName: plant-organ-segmentation-password
          key: plant-organ-segmentation-password
  parameters:
    objects: |
      - objectName: "arn:aws:secretsmanager:eu-west-2:824841205322:secret:mas-secrets-production-ZE1Eg4"
        jmesPath:
            - path: "geopick_user"
              objectAlias: "geopick-user"
            - path: "geopick_password"
              objectAlias: "geopick-password"
            - path: "bold_api_user"
              objectAlias: "bold-api-user"
            - path: "bold_api_password"
              objectAlias: "bold-api-password"
            - path: "mindat_api_key"
              objectAlias: "mindat-api-key"
            - path: "plant_organ_segmentation_user"
              objectAlias: "plant-organ-segmentation-user"
            - path: "plant_organ_segmentation_password"
              objectAlias: "plant-organ-segmentation-password"