apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter-argocd
  namespace: argocd
spec:
  project: default
  source:
    chart: karpenter
    repoURL: public.ecr.aws/karpenter
    targetRevision: 1.0.8
    helm:
      releaseName: karpenter
      values: |
        serviceAccount:
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::824841205322:role/KarpenterControllerRole-dissco-k8s-helm
        settings:
          clusterName: dissco-k8s-acc
        controller:
          resources:
            requests:
              cpu: 1
              memory: 1Gi
            limits:
              cpu: 1
              memory: 1Gi
        dnsPolicy: ClusterFirst
        webhook:
          enabled: true
          port: 8443
  destination:
    server: "https://kubernetes.default.svc"
    namespace: karpenter
