apiVersion: v1
kind: ServiceAccount
metadata:
  name: mas-secret-manager
  namespace: machine-annotation-services
  annotations: {
    eks.amazonaws.com/role-arn: "arn:aws:iam::824841205322:role/secret-manager-acc"
  }
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-secrets-mas
subjects:
  - kind: ServiceAccount
    name: mas-secret-manager
    namespace: machine-annotation-services
roleRef:
  kind: ClusterRole
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io