apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: default
spec:
  provider: aws
  secretObjects:
    - secretName: aws-secrets
      type: Opaque
      data:
        - objectName: elastic-username
          key: elastic-username
        - objectName: elastic-password
          key: elastic-password
        - objectName: mongodb-connection
          key: mongodb-connection
        - objectName: pid-mongodb-connection
          key: pid-mongodb-connection
        - objectName: indexing-col-password
          key: indexing-col-password
        - objectName: col-bucket-access-key-id
          key: col-bucket-access-key-id
        - objectName: col-bucket-access-key-secret
          key: col-bucket-access-key-secret
        - objectName: ses-access-key
          key: ses-access-key
        - objectName: ses-access-key-secret
          key: ses-access-key-secret
        - objectName: datacite-repository-id
          key: datacite-repository-id
        - objectName: datacite-password
          key: datacite-password
        - objectName: production-dissco-processor-token
          key: production-dissco-processor-token
        - objectName: production-dissco-orchestration-token
          key: production-dissco-orchestration-token
        - objectName: production-dissco-backend-token
          key: production-dissco-backend-token
        - objectName: rabbitmq-username
          key: rabbitmq-username
        - objectName: rabbitmq-password
          key: rabbitmq-password
        - objectName: rabbitmq-host-full
          key: rabbitmq-host-full
        - objectName: orchestration-s3-access-key
          key: orchestration-s3-access-key
        - objectName: orchestration-s3-access-key-secret
          key: orchestration-s3-access-key-secret
  parameters:
    objects: |
      - objectName: "arn:aws:secretsmanager:eu-west-2:824841205322:secret:dissco-prod-secrets-3rW8Id"
        jmesPath:
            - path: "elastic_username"
              objectAlias: "elastic-username"
            - path: "elastic_password"
              objectAlias: "elastic-password"
            - path: "mongodb_connection"
              objectAlias: "mongodb-connection"
            - path: "pid_mongodb_connection"
              objectAlias: "pid-mongodb-connection"
            - path: "indexing_col_password"
              objectAlias: "indexing-col-password"
            - path: "col_bucket_access_key_id"
              objectAlias: "col-bucket-access-key-id"
            - path: "col_bucket_access_key_secret"
              objectAlias: "col-bucket-access-key-secret"
            - path: "ses_access_key"
              objectAlias: "ses-access-key"
            - path: "ses_access_key_secret"
              objectAlias: "ses-access-key-secret"
            - path: "datacite_repository_id"
              objectAlias: "datacite-repository-id"
            - path: "datacite_password"
              objectAlias: "datacite-password"
            - path: "production_dissco_processor_token"
              objectAlias: "production-dissco-processor-token"
            - path: "production_dissco_orchestration_token"
              objectAlias: "production-dissco-orchestration-token"
            - path: "production_dissco_backend_token"
              objectAlias: "production-dissco-backend-token"
            - path: "rabbitmq_username"
              objectAlias: "rabbitmq-username"
            - path: "rabbitmq_password"
              objectAlias: "rabbitmq-password"
            - path: "rabbitmq_host_full"
              objectAlias: "rabbitmq-host-full"
            - path: "orchestration_s3_access_key"
              objectAlias: "orchestration-s3-access-key"
            - path: "orchestration_s3_access_key_secret"
              objectAlias: "orchestration-s3-access-key-secret"