apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: db-secrets
  namespace: default
spec:
  provider: aws
  secretObjects:
    - secretName: db-secrets
      type: Opaque
      data:
        - objectName: db-username
          key: db-username
        - objectName: db-password
          key: db-password
  parameters:
    # Todo - set secret arn
    objects: |
      - objectName: "" 
        jmesPath:
            - path: "username"
              objectAlias: "db-username"
            - path: "password"
              objectAlias: "db-password"
