apiVersion: v1
kind: Service
metadata:
  name: dissco-orchestration-backend-service
spec:
  selector:
    app: dissco-orchestration-backend
  ports:
    - protocol: TCP
      port: 8080
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: dissco-orchestration-backend-route
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`orchestration.dissco.tech`) && PathPrefix(`/api`)
      kind: Rule
      services:
        - name: dissco-orchestration-backend-service
          namespace: default
          port: 8080
      middlewares:
        - name: dissco-orchestration-backend-stripprefix-for-frontend
        - name: dissco-orchestration-backend-cors-headers
    - match: Host(`api.dissco.eu`) && PathPrefix(`/data-mapping/v1`)
      kind: Rule
      services:
        - name: dissco-orchestration-backend-service
          namespace: default
          port: 8080
      middlewares:
        - name: dissco-orchestration-backend-cors-headers
    - match: Host(`api.dissco.eu`) && PathPrefix(`/mas/v1`)
      kind: Rule
      services:
        - name: dissco-orchestration-backend-service
          namespace: default
          port: 8080
      middlewares:
        - name: dissco-orchestration-backend-cors-headers
    - match: Host(`api.dissco.eu`) && PathPrefix(`/source-system/v1`)
      kind: Rule
      services:
        - name: dissco-orchestration-backend-service
          namespace: default
          port: 8080
      middlewares:
        - name: dissco-orchestration-backend-cors-headers
    - match: Host(`api.dissco.eu`) && PathPrefix(`/orchestration`)
      kind: Rule
      services:
        - name: dissco-orchestration-backend-service
          namespace: default
          port: 8080
      middlewares:
        - name: dissco-orchestration-backend-health-stripprefix
    - match: Host(`disscover.dissco.eu`) && PathPrefix(`/api/source-system/v1`)
      kind: Rule
      services:
        - name: dissco-orchestration-backend-service
          namespace: default
          port: 8080
      middlewares:
        - name: dissco-orchestration-backend-stripprefix-for-frontend
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: dissco-orchestration-backend-stripprefix-for-frontend
spec:
  stripPrefix:
    prefixes:
      - /api
    forceSlash: false
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: dissco-orchestration-backend-health-stripprefix
spec:
  stripPrefix:
    prefixes:
      - /orchestration
    forceSlash: false
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: dissco-orchestration-backend-cors-headers
spec:
  headers:
    accessControlAllowMethods:
      - "GET"
    accessControlAllowHeaders:
      - "*"
    accessControlAllowOriginList:
      - "*"
    accessControlMaxAge: 100
    addVaryHeader: true