apiVersion: v1
kind: ServiceAccount
metadata:
  name: dissco-orchestration-backend-sa
  annotations: {
    eks.amazonaws.com/role-arn: "arn:aws:iam::824841205322:role/secret-manager-acc"
  }
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: dissco-orchestration-backend-role
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [ "batch" ] # "" indicates the core API group
    resources: [ "jobs" ]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dissco-orchestration-backend-role
  namespace: default
subjects:
  - kind: ServiceAccount
    name: dissco-orchestration-backend-sa
    namespace: default
roleRef:
  kind: Role
  name: dissco-orchestration-backend-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: translator-services
  name: orchestration-backend-translator-role
rules:
  - apiGroups: ["batch"] # "" indicates the core API group
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [ "batch" ] # "" indicates the core API group
    resources: [ "cronjobs" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: translator-admin-role
  namespace: translator-services
subjects:
  - kind: ServiceAccount
    name: dissco-orchestration-backend-sa
    namespace: default
roleRef:
  kind: Role
  name: orchestration-backend-translator-role
  apiGroup: rbac.authorization.k8s.io