apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acceptance-deployment
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: acceptance
    repoURL: https://github.com/DiSSCo/dissco-core-deployment.git
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    automated: { }
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas