apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::824841205322:role/managed_nodes-eks-node-group-20241126142334865500000001
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::824841205322:role/KarpenterNodeRole-dissco-k8s-acc
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - system:masters
      userarn: arn:aws:iam::824841205322:user/tom.dijkema@naturalis.nl
    - groups:
      - system:masters
      userarn: arn:aws:iam::824841205322:user/soulaine.theocharides@naturalis.nl
    - groups:
      - system:masters
      userarn: arn:aws:iam::824841205322:user/sam.leeflang@naturalis.nl
