apiVersion: apps/v1
kind: Deployment
metadata:
  name: disscover
  labels:
    app: disscover
spec:
  replicas: 1
  selector:
    matchLabels:
      app: disscover
  template:
    metadata:
      labels:
        app: disscover
    spec:
      automountServiceAccountToken: false
      containers:
        - name: disscover
          image: ppublic.ecr.aws/dissco/disscover:sha-47b9898 # Nov 25
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "100Mi"
              cpu: "200m"
              # todo ephemeral storage?
      restartPolicy: Always