apiVersion: v1
kind: ServiceAccount
metadata:
  name: data-exporter-backend-service-account
  annotations: {
    eks.amazonaws.com/role-arn: "arn:aws:iam::824841205322:role/secret-manager-acc"
  }
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: data-export-job
  name: data-export-create-resources
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: data-export-job
  name: data-export-admin-role
subjects:
  - kind: ServiceAccount
    name: data-exporter-backend-service-account
    namespace: default
roleRef:
  kind: Role
  name: data-export-create-resources
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-secrets-data-exporter-backend
subjects:
  - kind: ServiceAccount
    name: data-exporter-backend-service-account
    namespace: default
roleRef:
  kind: ClusterRole
  name: secret-manager
  apiGroup: rbac.authorization.k8s.io