apiVersion: v1
kind: Service
metadata:
  name: dissco-backend-service
spec:
  selector:
    app: dissco-backend
  ports:
    - protocol: TCP
      port: 8080
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: dissco-backend-route
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`disscover.dissco.eu`) && PathPrefix(`/api`)
      kind: Rule
      services:
        - name: dissco-backend-service
          namespace: default
          port: 8080
      middlewares:
        - name: dissco-backend-cors-headers
        - name: dissco-backend-stripprefix
    - match: Host(`api.dissco.eu`) && PathPrefix(`/annotation/v1`)
      kind: Rule
      services:
        - name: dissco-backend-service
          namespace: default
          port: 8080
      middlewares:
        - name: dissco-backend-cors-headers
    - match: Host(`api.dissco.eu`) && PathPrefix(`/digital-media/v1`)
      kind: Rule
      services:
        - name: dissco-backend-service
          namespace: default
          port: 8080
      middlewares:
        - name: dissco-backend-cors-headers
    - match: Host(`api.dissco.eu`) && PathPrefix(`/digital-specimen/v1`)
      kind: Rule
      services:
        - name: dissco-backend-service
          namespace: default
          port: 8080
      middlewares:
        - name: dissco-backend-cors-headers
    - match: Host(`api.dissco.eu`) && PathPrefix(`/mjr/v1`)
      kind: Rule
      services:
        - name: dissco-backend-service
          namespace: default
          port: 8080
      middlewares:
        - name: dissco-backend-cors-headers
    - match : Host(`api.dissco.eu`) && PathPrefix(`/backend`)
      kind: Rule
      services:
        - name: dissco-backend-service
          namespace: default
          port: 8080
      middlewares:
        - name: dissco-backend-health-stripprefix
        - name: dissco-backend-cors-headers
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: dissco-backend-stripprefix
spec:
  stripPrefix:
    prefixes:
      - /api
    forceSlash: false
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: dissco-backend-health-stripprefix
spec:
  stripPrefix:
    prefixes:
      - /backend
    forceSlash: false
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: dissco-backend-cors-headers
spec:
  headers:
    accessControlAllowMethods:
      - "GET"
    accessControlAllowHeaders:
      - "*"
    accessControlAllowOriginList:
      - "*"
    accessControlMaxAge: 100
    addVaryHeader: true