apiVersion: v1
kind: ConfigMap
metadata:
  name: migration-configmap
  namespace: flyway
  annotations:
    argocd.argoproj.io/hook: PreSync
data:
  V1_2_7__add_annotation_status.sql: |
    create type annotation_status_enum as enum ('ACCEPTED', 'MERGED', 'PENDING', 'REJECTED', 'TOMBSTONED');
    alter table public.annotation add annotation_status annotation_status_enum;
    create index annotation_status_index on annotation(target_id, annotation_status);
  V1_2_5__virtual_collection_table.sql: |
    create type collection_type as enum ('REFERENCE_COLLECTION', 'COMMUNITY_COLLECTION');
    create table virtual_collection
    (
        id              text                     not null
            primary key,
        version         integer default 1        not null,
        name            text                     not null,
        collection_type collection_type          not null,
        created         timestamp with time zone not null,
        modified        timestamp with time zone not null,
        tombstoned      timestamp with time zone,
        creator         text                     not null,
        data            jsonb                    not null
    );
  V1_2_4__add_unique_constraints_to_source_system.sql: |
    ALTER TABLE public.source_system
    ADD CONSTRAINT endpoint_unique UNIQUE NULLS NOT DISTINCT (endpoint, tombstoned, filters);
    ALTER TABLE public.source_system
    ADD CONSTRAINT name_unique UNIQUE (name);
  V1_2_3__add_temp_doi_table.sql: |
    create table manual_pid
    (
        pid      text,
        prefix   text
    );
    comment on table manual_pid is 'PIDs from which the PID manager may pull';
    comment on column manual_pid.pid is 'Persistent identifier';
    comment on column manual_pid.prefix is 'One of: TEST, SANDBOX, 20.5000.1025, 10.3535';
  V1_2_2__update_annotation_target_index.sql: |
    DROP INDEX public.annotation_id_target_id_index;
    CREATE INDEX annotation_target_id_index ON public.annotation (target_id);
  V1_2_1__update_test_table.sql: |
    ALTER TABLE public.source_system
    ADD COLUMN filters TEXT[];