apiVersion: v1
kind: ConfigMap
metadata:
  name: migration-configmap
  namespace: flyway
  annotations:
    argocd.argoproj.io/hook: PreSync
data:
  V1_2_1__update_test_table.sql: |
    ALTER TABLE public.source_system
    ADD COLUMN filters TEXT[];