apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: traefik-ingress-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traefik-ingress-controller
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
      - ingressclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses/status
    verbs:
      - update
  - apiGroups:
      - traefik.io
      - traefik.containo.us
    resources:
      - middlewares
      - middlewaretcps
      - ingressroutes
      - traefikservices
      - ingressroutetcps
      - ingressrouteudps
      - tlsoptions
      - tlsstores
      - serverstransports
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: traefik-ingress-controller

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-ingress-controller
subjects:
  - kind: ServiceAccount
    name: traefik-ingress-controller
    namespace: default
---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: traefik
  labels:
    app: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      automountServiceAccountToken: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: eks.amazonaws.com/nodegroup
                    operator: In
                    values:
                      - managed_m5-20230823065304717700000010
      containers:
        - name: traefik
          image: traefik:v2.11
          resources:
            requests:
              memory: "250Mi"
              cpu: "100m"
            limits:
              memory: "250Mi"
              cpu: "200m"
              ephemeral-storage: "1Gi"
          args:
            - --accesslog
            - --entrypoints.web.Address=:80
            - --entrypoints.web.http.redirections.entryPoint.to=websecure
            - --entrypoints.web.http.redirections.entryPoint.scheme=https
            - --entrypoints.web.http.redirections.entrypoint.permanent=true
            - --entrypoints.websecure.Address=:443
            - --entrypoints.websecure.http.tls.certresolver=defaultresolver
            - --entrypoints.websecure.http.middlewares=default-security-middleware@kubernetescrd
            - --entrypoints.websecure.http.tls.options=default-tls-option@kubernetescrd
            - --entrypoints.web.forwardedheaders.insecure=true
            - --entrypoints.websecure.forwardedheaders.insecure=true
            - --providers.kubernetescrd
            - --certificatesresolvers.defaultresolver.acme.tlschallenge
            - --certificatesresolvers.defaultresolver.acme.email=sam.leeflang@naturalis.nl
            - --certificatesresolvers.defaultresolver.acme.storage=/cert/acme.json
            - --metrics.prometheus=true
            - --providers.kubernetescrd.allowcrossnamespace=true
            - --log.level=INFO
            - --accesslog.fields.headers.defaultmode=keep
          ports:
            - name: web
              containerPort: 80
            - name: websecure
              containerPort: 443
          volumeMounts:
            - mountPath: "/cert"
              name: cert-storage
      volumes:
        - name: cert-storage
          persistentVolumeClaim:
            claimName: cert-storage-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cert-storage-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi