apiVersion: v1
kind: ConfigMap
metadata:
  name: migration-configmap
  namespace: flyway
  annotations:
    argocd.argoproj.io/hook: PreSync
data:
  V1_3_6__add_translator_report_and_virtual_collections_countries.sql: |
    ALTER TABLE translator_job_record
    ADD report jsonb;
    ALTER TABLE virtual_collection
    ADD COLUMN countries text[];