apiVersion: apps/v1
kind: Deployment
metadata:
  name: datacite-publisher
  labels:
    app: datacite-publisher-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datacite-publisher
  template:
    metadata:
      labels:
        app: datacite-publisher
        language: java
      annotations:
        co.elastic.logs/multiline.pattern: '^[[:space:]]+(at|\.{3})[[:space:]]+\b|^Caused by:'
        co.elastic.logs/multiline.negate: "false"
        co.elastic.logs/multiline.match: after
    spec:
      serviceAccountName: secret-manager
      automountServiceAccountToken: false
      containers:
        - name: datacite-publisher
          image: public.ecr.aws/dissco/datacite-publisher:sha-62857f6
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: doi.prefix
              value: '10.82621'
            - name: spring.security.oauth2.resourceserver.jwt.issuer-uri
              value: https://login-demo.dissco.eu/auth/realms/dissco
            - name: spring.security.oauth2.authorizationserver.endpoint.jwk-set-uri
              value: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
            - name: datacite.endpoint
              value: https://api.test.datacite.org/dois
            - name: datacite.repository-id
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: datacite-repository-id
            - name: datacite.password
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: datacite-password
            - name: kafka.consumer.topic.specimen
              value: specimen-doi
            - name: kafka.consumer.topic.media
              value: media-doi
            - name: kafka.consumer.topic.tombstone
              value: tombstone
            - name: spring.kafka.consumer.group-id
              value: group-1
            - name: kafka.consumer.host
              value: kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
            - name: kafka.consumer.group
              value: group-1
          resources:
            requests:
              memory: "500Mi"
              cpu: "200m"
            limits:
              memory: "500Mi"
              cpu: "750m"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 45
            failureThreshold: 2
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
      volumes:
        - name: aws-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "aws-secrets"