services:
  doi_server:
    container_name: doi-server
    image: doi_server:latest
    network_mode: "host"
    restart: always
    volumes:
      - type: bind
        source: ${SRC_KEYS}/admpriv.bin
        target: ${TGT_KEYS}/admpriv.bin
      - type: bind
        source: ${SRC_KEYS}/privkey.bin
        target: ${TGT_KEYS}/privkey.bin
      - type: bind
        source: ${SRC_KEYS}/config.dct
        target: ${TGT_KEYS}/config.dct
      - type: bind
        source: ${SRC_KEYS}/serverCertificate.pem
        target: ${TGT_KEYS}/serverCertificate.pem
      - type: bind
        source: ${SRC_KEYS}/siteinfo.json
        target: ${TGT_KEYS}/siteinfo.json
      - type: bind
        source: ${SRC_KEYS}/sitebndl.zip
        target: ${TGT_KEYS}/sitebndl.zip

  doi_api:
    container_name: doi-api
    image: public.ecr.aws/dissco/handle-manager:sha-4e6785c #Oct 2, 2023
    restart: always
    environment:
      spring.security.oauth2.resourceserver.jwt.issuer-uri: ${JWT_ISSUER}
      spring.security.oauth2.authorizationserver.endpoint.jwk-set-uri: ${JWK_URI}
      application.ui-url: ${UI_URL}
      application.api-url: ${API_URL}
      application.orchestration-url: ${ORCHESTRATION_URL}
      application.maxHandles: ${MAX_HANDLES}
      spring.datasource.url: ${DB_URL}
      spring.profiles.active: doi
      spring.datasource.username: ${DB_USR}
      spring.datasource.password: ${DB_PWD}
      springdoc.swagger-ui.operationsSorter: ${SWAGGER_SORT}
      application.prefix: ${PREFIX}
      server.port: 8081

  nginx-proxy:
    image: nginx:1.25.2
    container_name: nginx
    restart: always
    depends_on:
      - doi_api
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/nginx/:/etc/nginx/conf.d/:ro
      - ./data/certbot/conf/:/etc/nginx/ssl/:ro
      - ./data/certbot/www:/var/www/certbot/:ro
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    volumes:
      - ./data/certbot/conf/:/etc/letsencrypt/:rw
      - ./data/certbot/www/:/var/www/certbot/:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
