apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: db-secrets-flyway
  namespace: flyway
spec:
  provider: aws
  secretObjects:
    - secretName: db-secrets-flyway
      type: Opaque
      data:
        - objectName: db-username
          key: db-username
        - objectName: db-password
          key: db-password
  parameters:
    objects: |
      - objectName: "arn:aws:secretsmanager:eu-west-2:824841205322:secret:dissco-prod-secrets-3rW8Id"
        jmesPath:
            - path: "username"
              objectAlias: "db-username"
            - path: "password"
              objectAlias: "db-password"
