apiVersion: batch/v1
kind: Job
metadata:
  generateName: db-migration-
  namespace: flyway
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      serviceAccountName: flyway-secret-manager
      automountServiceAccountToken: true
      containers:
        - name: flyway
          image: redgate/flyway:11-alpine
          args:
            - info
            - repair
            - migrate
            - info
          env:
            - name: FLYWAY_URL
              value: ""
            - name: FLYWAY_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets-flyway
                  key: db-username
            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets-flyway
                  key: db-password
            - name: FLYWAY_BASELINE_ON_MIGRATE
              value: "true"
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
          volumeMounts:
          - mountPath: /flyway/sql
            name: sql
          - name: db-secrets-flyway
            mountPath: "/mnt/secrets-store/db-secrets-flyway"
            readOnly: true
      volumes:
        - name: sql
          configMap:
            name: migration-configmap
        - name: db-secrets-flyway
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "db-secrets-flyway"
      restartPolicy: Never