apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: default
spec:
  provider: aws
  secretObjects:
    - secretName: aws-secrets
      type: Opaque
      data:
        - objectName: elastic-username
          key: elastic-username
        - objectName: elastic-password
          key: elastic-password
        - objectName: mongodb-connection
          key: mongodb-connection
  parameters:
    objects: |
      - objectName: "arn:aws:secretsmanager:eu-west-2:824841205322:secret:dissco-acc-secrets-DhjNg7"
        jmesPath:
            - path: "elastic_username"
              objectAlias: "elastic-username"
            - path: "elastic_password"
              objectAlias: "elastic-password"
            - path: "mongodb_connection"
              objectAlias: "mongodb-connection"