apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: db-secrets
  namespace: default
spec:
  provider: aws
  secretObjects:
    - secretName: db-secrets
      type: Opaque
      data:
        - objectName: db-username
          key: db-username
        - objectName: db-password
          key: db-password
  parameters:
    objects: |
      - objectName: "arn:aws:secretsmanager:eu-west-2:824841205322:secret:rds!db-879f01f1-086d-4128-af59-7aebda2714c8-zq6KLX"
        jmesPath:
            - path: "username"
              objectAlias: "db-username"
            - path: "password"
              objectAlias: "db-password"
