apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-manager
  namespace: default
  annotations: {
    eks.amazonaws.com/role-arn: "arn:aws:iam::824841205322:role/secret-manager"
  }
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-manager
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["secrets"]
    verbs: ["*"]
