apiVersion: apps/v1
kind: Deployment
metadata:
  name: mas-scheduler-event
  labels:
    app: mas-scheduler-event
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mas-scheduler-event
  template:
    metadata:
      labels:
        app: mas-scheduler-event
        language: java
    spec:
      automountServiceAccountToken: false
      containers:
        - name: mas-scheduler-event
          image: public.ecr.aws/dissco/dissco-mas-scheduler-service:sha-60ac0a4  # Feb-04-2026
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: spring.profiles.active
              value: rabbitmq
            - name: spring.datasource.url
              value: jdbc:postgresql://terraform-20230828064251677200000001.cbppwfnjypll.eu-west-2.rds.amazonaws.com:5432/dissco
            - name: spring.datasource.username
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: db-username
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: db-password
            - name: spring.rabbitmq.password
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: rabbitmq-password
            - name: spring.rabbitmq.username
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: rabbitmq-username
            - name: spring.rabbitmq.host
              value: rabbitmq-cluster.rabbitmq.svc.cluster.local
            - name: rabbitmq.queue-name
              value: mas-scheduler-queue
            - name: spring.security.oauth2.resourceserver.jwt.issuer-uri
              value: https://keycloak.iam.naturalis.io/realms/dissco-dev
            - name: spring.security.oauth2.client.registration.dissco.authorization-grant-type
              value: client_credentials
            - name: spring.security.oauth2.client.provider.dissco.token-uri
              value: https://keycloak.iam.naturalis.io/realms/dissco-dev/protocol/openid-connect/token
            - name: endpoint.handleEndpoint
              value: https://sandbox.dissco.tech/handle-manager/api/pids/v1/
            - name: spring.security.oauth2.client.registration.dissco.client-id
              value: dissco-mas-scheduler
            - name: spring.security.oauth2.client.registration.dissco.client-secret
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: dissco-mas-scheduler-client-secret
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 60
            failureThreshold: 2
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: mas-scheduler-event-scaled-object
spec:
  scaleTargetRef:
    name: mas-scheduler-event
  minReplicaCount: 0
  maxReplicaCount:  1
  triggers:
    - type: rabbitmq
      metadata:
        mode: QueueLength
        value: "1"
        queueName: mas-scheduler-queue
      authenticationRef:
        name: keda-trigger-auth-rabbitmq-conn