apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: data-export-job
spec:
  provider: aws
  secretObjects:
    - secretName: aws-secrets
      type: Opaque
      data:
        - objectName: elastic-username
          key: elastic-username
        - objectName: elastic-password
          key: elastic-password
        - objectName: export-s3-access-key
          key: export-s3-access-key
        - objectName: export-s3-access-key-secret
          key: export-s3-access-key-secret
        - objectName: dissco-data-exporter-job-client-secret
          key: dissco-data-exporter-job-client-secret
        - objectName: export-client-id
          key: export-client-id
        - objectName: export-client-secret
          key: export-client-secret
  parameters:
    objects: |
      - objectName: "arn:aws:secretsmanager:eu-west-2:824841205322:secret:dissco-secrets-acc-DnW021"
        jmesPath:
            - path: "elastic_username"
              objectAlias: "elastic-username"
            - path: "elastic_password"
              objectAlias: "elastic-password"
            - path: "export_s3_access_key"
              objectAlias: "export-s3-access-key"
            - path: "export_s3_access_key_secret"
              objectAlias: "export-s3-access-key-secret"
            - path: "dissco_data_exporter_job_client_secret"
              objectAlias: "dissco-data-exporter-job-client-secret"
            - path: "export_client_id"
              objectAlias: "export-client-id"
            - path: "export_client_secret"
              objectAlias: "export-client-secret"