apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-operator-argocd
  namespace: argocd
spec:
  project: default
  source:
    chart: opentelemetry-operator
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    targetRevision: latest
    helm:
      releaseName: opentelemetry-operator
  destination:
    server: "https://kubernetes.default.svc"
    namespace: otel
  syncPolicy:
    syncOptions:
      - CreateNamespace=true