apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-telemetry-argocd
  namespace: argocd
spec:
  project: default
  source:
    chart: opentelemetry-operator
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    targetRevision: 0.74.0
    helm:
      releaseName: otel-collector-daemon
      values: |
        manager:
          collectorImage:
            repository: "otel/opentelemetry-collector-k8s"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: otel
  syncPolicy:
    syncOptions:
      - CreateNamespace=true