apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-node-exporter-argocd
  namespace: argocd
spec:
  project: default
  source:
    chart: prometheus-node-exporter
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 4.42.0
    helm:
      releaseName: prometheus-node-exporter
  destination:
    server: "https://kubernetes.default.svc"
    namespace: otel
  syncPolicy:
    syncOptions:
      - CreateNamespace=true