apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: data-export-job
spec:
  provider: aws
  secretObjects:
    - secretName: aws-secrets
      type: Opaque
      data:
        - objectName: elastic-username
          key: elastic-username
        - objectName: elastic-password
          key: elastic-password
        - objectName: export-s3-access-key
          key: export-s3-access-key
        - objectName: export-s3-access-key-secret
          key: export-s3-access-key-secret
        - objectName: production-dissco-data-export-job-token
          key: production-dissco-data-export-job-token
  parameters:
    objects: |
      - objectName: "arn:aws:secretsmanager:eu-west-2:824841205322:secret:dissco-prod-secrets-3rW8Id"
        jmesPath:
            - path: "elastic_username"
              objectAlias: "elastic-username"
            - path: "elastic_password"
              objectAlias: "elastic-password"
            - path: "export_s3_access_key"
              objectAlias: "export-s3-access-key"
            - path: "export_s3_access_key_secret"
              objectAlias: "export-s3-access-key-secret"
            - path: "production_dissco_data_export_job_token"
              objectAlias: "production-dissco-data-export-job-token"