apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: db-secrets
  namespace: data-export-job
spec:
  provider: aws
  secretObjects:
    - secretName: db-secrets
      type: Opaque
      data:
        - objectName: db-username
          key: db-username
        - objectName: db-password
          key: db-password
  parameters:
    objects: |
      - objectName: "arn:aws:secretsmanager:eu-west-2:824841205322:secret:rds!db-3a6a15a5-6067-4511-961f-3caf3fa1c6b5-udF8Gv" 
        jmesPath:
            - path: "username"
              objectAlias: "db-username"
            - path: "password"
              objectAlias: "db-password"
