apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: translator-services
spec:
  provider: aws
  secretObjects:
    - secretName: aws-secrets
      type: Opaque
      data:
        - objectName: rabbitmq-username
          key: rabbitmq-username
        - objectName: rabbitmq-password
          key: rabbitmq-password
        - objectName: rabbitmq-host-full
          key: rabbitmq-host-full
  parameters:
    objects: |
      - objectName: "arn:aws:secretsmanager:eu-west-2:824841205322:secret:dissco-secrets-acc-DnW021"
        jmesPath:
            - path: "rabbitmq_username"
              objectAlias: "rabbitmq-username"
            - path: "rabbitmq_password"
              objectAlias: "rabbitmq-password"
            - path: "rabbitmq_host_full"
              objectAlias: "rabbitmq-host-full"