apiVersion: v1
kind: ServiceAccount
metadata:
  name: translator-secret-manager
  namespace: translator-services
  annotations: {
    eks.amazonaws.com/role-arn: "arn:aws:iam::824841205322:role/secret-manager-acc"
  }
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-manager
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["secrets"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-secrets-global
subjects:
  - kind: ServiceAccount
    name: translator-secret-manager
    namespace: translator-services
roleRef:
  kind: ClusterRole
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io